function [Y,Xf,Af] = myNeuralNetworkFunction(X,~,~)
%MYNEURALNETWORKFUNCTION neural network simulation function.
%
% Auto-generated by MATLAB, 08-Sep-2019 21:07:46.
%
% [Y] = myNeuralNetworkFunction(X,~,~) takes these arguments:
%
%   X = 1xTS cell, 1 inputs over TS timesteps
%   Each X{1,ts} = Qx4 matrix, input #1 at timestep ts.
%
% and returns:
%   Y = 1xTS cell of 1 outputs over TS timesteps.
%   Each Y{1,ts} = Qx3 matrix, output #1 at timestep ts.
%
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = [20000000;0.15;0.422618261740699;0.108866874851965];
x1_step1.gain = [2.5e-08;6.66666666666667;7.03016066833128;4.4772441563993];
x1_step1.ymin = -1;

% Layer 1
b1 = [-2.2397747816665192211;2.0829626869940862655;-2.2686467504114204985;-2.2737210754991719064;-0.61194710483094150177;-4.2315556474295341616;3.8132391037430504177;-0.8929653911905632846;1.4225255689993270281;-2.4703845839747278212];
IW1_1 = [1.5940832307741430451 0.23148780086389517119 -2.123018107310224778 -0.63986507535594683294;-3.7021097184839031335 0.38316251063974793301 -0.87223352173280743749 0.93978246820156274843;1.1013378771579558357 0.76524933102403880358 -0.61455604528761920147 1.7435070197680975213;2.1411243613782011685 0.54059806148315736607 0.44071997412097413394 -0.014378643016738607008;-2.3750552773720241539 3.5365136552995006802 0.8471110157668199081 0.15733587462715792338;-0.36047768551937453552 5.9280075347877634329 1.3783568391817908605 0.29150653467117143558;2.9260369655927358501 -6.347909888039209747 -1.1737982063504270869 -0.30750245633004802404;-3.4992379402360187512 -1.2072108744362679555 1.0730999883866543243 -0.43118719761872509322;2.7062539791507864706 1.6098754946811923983 1.1509006353852271332 -0.089038044272922473032;-1.8235935483894347708 -0.94817325891056303266 -0.073498965022263065827 1.8064153059447258798];

% Layer 2
b2 = [2.6485906622040227276;-1.8647982015504520614;-2.5804111171896275678];
LW2_1 = [-0.29815265564974219314 0.22988778823204206181 0.65223340234498816681 0.56530133344019173336 -4.8887524760952461023 4.1384721331014873158 -0.091037253436626691672 1.2604966362254368395 -0.51778364016973099648 -0.30247673655796575298;-0.048130949386921376143 -1.0199838790991329063 -0.62745521481980659484 -0.097254800936753330043 0.28168840177668907909 -3.8900983964445003949 -4.576354871226618215 -1.831608843916823659 0.85083217566116053909 1.8669486242885051652;-0.044326902570113839441 1.2792525233281877295 0.31644793913272795116 -1.1635961701554520253 4.4004510922227542125 0.43578116362200258749 5.2931570378231418417 0.37687385196052647363 -0.30607724425084642528 -0.46480359961301959126];

% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX
    X = {X};
end

% Dimensions
TS = size(X,2); % timesteps
if ~isempty(X)
    Q = size(X{1},1); % samples/series
else
    Q = 0;
end

% Allocate Outputs
Y = cell(1,TS);

% Time loop
for ts=1:TS
    
    % Input 1
    X{1,ts} = X{1,ts}';
    Xp1 = mapminmax_apply(X{1,ts},x1_step1);
    
    % Layer 1
    a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*Xp1);
    
    % Layer 2
    a2 = softmax_apply(repmat(b2,1,Q) + LW2_1*a1);
    
    % Output 1
    Y{1,ts} = a2;
    Y{1,ts} = Y{1,ts}';
end

% Final Delay States
Xf = cell(1,0);
Af = cell(2,0);

% Format Output Arguments
if ~isCellX
    Y = cell2mat(Y);
end
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
y = bsxfun(@minus,x,settings.xoffset);
y = bsxfun(@times,y,settings.gain);
y = bsxfun(@plus,y,settings.ymin);
end

% Competitive Soft Transfer Function
function a = softmax_apply(n,~)
if isa(n,'gpuArray')
    a = iSoftmaxApplyGPU(n);
else
    a = iSoftmaxApplyCPU(n);
end
end
function a = iSoftmaxApplyCPU(n)
nmax = max(n,[],1);
n = bsxfun(@minus,n,nmax);
numerator = exp(n);
denominator = sum(numerator,1);
denominator(denominator == 0) = 1;
a = bsxfun(@rdivide,numerator,denominator);
end
function a = iSoftmaxApplyGPU(n)
nmax = max(n,[],1);
numerator = arrayfun(@iSoftmaxApplyGPUHelper1,n,nmax);
denominator = sum(numerator,1);
a = arrayfun(@iSoftmaxApplyGPUHelper2,numerator,denominator);
end
function numerator = iSoftmaxApplyGPUHelper1(n,nmax)
numerator = exp(n - nmax);
end
function a = iSoftmaxApplyGPUHelper2(numerator,denominator)
if (denominator == 0)
    a = numerator;
else
    a = numerator ./ denominator;
end
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
a = 2 ./ (1 + exp(-2*n)) - 1;
end
